name: Pterodactyl-Ubuntu

on:
  workflow_dispatch:
    inputs:
      imagename:
        description: 'Image Name'
        required: true
        default: 'error'
      imageversion:
        description: 'Version of the docker image'
        required: true
        default: '1.0'
      imagedir:
        description: 'Directory of the image'
        required: true
        default: 'default'
      platform:
        description: 'Egg platforms. amd64 for AMD64, arm64 for Arm64, and both for both of them'
        required: true
        default: 'both'

jobs:
  push:
    name: "nginx-ptero:${{ github.event.inputs.imagename }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "${{ github.event.inputs.imageversion }}"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PUSH_TOKEN }}
      - if: github.event.inputs.platform == 'both'
        uses: docker/build-push-action@v2
        with:
          context: ./${{ github.event.inputs.imagedir }}/
          file: ./${{ github.event.inputs.imagedir }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/JohnB17/nginx-ptero:${{ github.event.inputs.imagename }}
      - if: github.event.inputs.platform == 'amd64'
        uses: docker/build-push-action@v2
        with:
          context: ./${{ github.event.inputs.imagedir }}/
          file: ./${{ github.event.inputs.imagedir }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/JohnB17/nginx-ptero:${{ github.event.inputs.imagename }}
      - if: github.event.inputs.platform == 'arm64'
        uses: docker/build-push-action@v2
        with:
          context: ./${{ github.event.inputs.imagedir }}/
          file: ./${{ github.event.inputs.imagedir }}/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/JohnB17/nginx-ptero:${{ github.event.inputs.imagename }}
